# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 997)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 0))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setStyleSheet("background-color: rgb(160, 43, 51)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(50, 30))
        self.label.setMaximumSize(QtCore.QSize(50, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../SPSCloud_app/img/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("text-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setStyleSheet("#frame_3 {border: 0px;}\n"
"\n"
"QFrame {border: 0px solid rgb(158, 159, 159);      /* Light gray border */\n"
"    border-radius: 0px;            /* Rounded corners */}\n"
"\n"
"QPushButton {\n"
"    background-color: #A02B33;  /* Main new color */\n"
"    border: none;               /* No border */\n"
"    color: white;               /* White text color */\n"
"    padding: 8px 15px;         /* Padding around text */\n"
"    font: bold 16px;           /* Bold font with size 16 */\n"
"    border-radius: 5px;        /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8E2731; /* Slightly darker shade of new color when mouse hovers over */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7C1D25; /* Even darker shade of new color when button is pressed */\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setMinimumSize(QtCore.QSize(800, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.line_3 = QtWidgets.QFrame(self.frame_2)
        self.line_3.setMinimumSize(QtCore.QSize(10, 2))
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 2))
        font = QtGui.QFont()
        font.setBold(True)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("background-color: rgb(36, 86, 74);\n"
"\n"
" ")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_11.addWidget(self.line_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.apps_2 = QtWidgets.QFrame(self.frame_4)
        self.apps_2.setMinimumSize(QtCore.QSize(100, 0))
        self.apps_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.apps_2.setStyleSheet("")
        self.apps_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.apps_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.apps_2.setObjectName("apps_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.apps_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.app2_1 = QtWidgets.QFrame(self.apps_2)
        self.app2_1.setMinimumSize(QtCore.QSize(200, 0))
        self.app2_1.setStyleSheet("#app2_1 {border: 1px solid rgb(158, 159, 159);      /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */}\n"
"\n"
"")
        self.app2_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app2_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app2_1.setObjectName("app2_1")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.app2_1)
        self.horizontalLayout_17.setContentsMargins(-1, 20, -1, 20)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.appp1_5 = QtWidgets.QFrame(self.app2_1)
        self.appp1_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.appp1_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.appp1_5.setStyleSheet("")
        self.appp1_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.appp1_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.appp1_5.setObjectName("appp1_5")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.appp1_5)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_38 = QtWidgets.QLabel(self.appp1_5)
        self.label_38.setMinimumSize(QtCore.QSize(150, 150))
        self.label_38.setMaximumSize(QtCore.QSize(150, 150))
        self.label_38.setStyleSheet("\n"
"border: 4px;\n"
"border-color:  rgb(102, 255, 139);\n"
"border-radius: 20px;        /* Rounded corners */\n"
"")
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("../SPSCloud_app/img/apps/1.png"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_27.addWidget(self.label_38, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_39 = QtWidgets.QLabel(self.appp1_5)
        self.label_39.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_18.addWidget(self.label_39)
        self.progressBar_5 = QtWidgets.QProgressBar(self.appp1_5)
        self.progressBar_5.setProperty("value", 85)
        self.progressBar_5.setObjectName("progressBar_5")
        self.horizontalLayout_18.addWidget(self.progressBar_5)
        self.verticalLayout_27.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17.addWidget(self.appp1_5)
        self.widget_7 = QtWidgets.QWidget(self.app2_1)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_40 = QtWidgets.QLabel(self.widget_7)
        self.label_40.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_40.setObjectName("label_40")
        self.verticalLayout_28.addWidget(self.label_40)
        self.label_13 = QtWidgets.QLabel(self.widget_7)
        self.label_13.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_28.addWidget(self.label_13)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_10.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_10.setMaximumSize(QtCore.QSize(150, 35))
        self.pushButton_10.setStyleSheet("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_28.addWidget(self.pushButton_10)
        self.horizontalLayout_17.addWidget(self.widget_7)
        self.verticalLayout_8.addWidget(self.app2_1)
        self.app2_2 = QtWidgets.QFrame(self.apps_2)
        self.app2_2.setStyleSheet("#app2_2 {border: 1px solid rgb(158, 159, 159);      /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */}\n"
"\n"
"")
        self.app2_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app2_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app2_2.setObjectName("app2_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.app2_2)
        self.horizontalLayout_19.setContentsMargins(-1, 20, -1, 20)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.appp1_6 = QtWidgets.QFrame(self.app2_2)
        self.appp1_6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.appp1_6.setSizeIncrement(QtCore.QSize(0, 0))
        self.appp1_6.setStyleSheet("")
        self.appp1_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.appp1_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.appp1_6.setObjectName("appp1_6")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.appp1_6)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_41 = QtWidgets.QLabel(self.appp1_6)
        self.label_41.setMinimumSize(QtCore.QSize(150, 150))
        self.label_41.setMaximumSize(QtCore.QSize(150, 150))
        self.label_41.setStyleSheet("\n"
"border: 4px;\n"
"border-color:  rgb(102, 255, 139);\n"
"border-radius: 20px;        /* Rounded corners */\n"
"")
        self.label_41.setText("")
        self.label_41.setPixmap(QtGui.QPixmap("../SPSCloud_app/img/apps/3.png"))
        self.label_41.setScaledContents(True)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_29.addWidget(self.label_41, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_42 = QtWidgets.QLabel(self.appp1_6)
        self.label_42.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_20.addWidget(self.label_42)
        self.progressBar_6 = QtWidgets.QProgressBar(self.appp1_6)
        self.progressBar_6.setStyleSheet("")
        self.progressBar_6.setProperty("value", 5)
        self.progressBar_6.setObjectName("progressBar_6")
        self.horizontalLayout_20.addWidget(self.progressBar_6)
        self.verticalLayout_29.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19.addWidget(self.appp1_6)
        self.widget_8 = QtWidgets.QWidget(self.app2_2)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_43 = QtWidgets.QLabel(self.widget_8)
        self.label_43.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_43.setObjectName("label_43")
        self.verticalLayout_30.addWidget(self.label_43)
        self.label_14 = QtWidgets.QLabel(self.widget_8)
        self.label_14.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_30.addWidget(self.label_14)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_11.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_11.setMaximumSize(QtCore.QSize(150, 35))
        self.pushButton_11.setStyleSheet("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_30.addWidget(self.pushButton_11)
        self.horizontalLayout_19.addWidget(self.widget_8)
        self.verticalLayout_8.addWidget(self.app2_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.horizontalLayout_8.addWidget(self.apps_2)
        self.apps_1 = QtWidgets.QFrame(self.frame_4)
        self.apps_1.setMinimumSize(QtCore.QSize(100, 0))
        self.apps_1.setMaximumSize(QtCore.QSize(500, 16777215))
        self.apps_1.setStyleSheet("")
        self.apps_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.apps_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.apps_1.setObjectName("apps_1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.apps_1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.app1_1 = QtWidgets.QFrame(self.apps_1)
        self.app1_1.setMinimumSize(QtCore.QSize(200, 0))
        self.app1_1.setStyleSheet("#app1_1 {border: 1px solid rgb(158, 159, 159);      /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */}\n"
"\n"
"")
        self.app1_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app1_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app1_1.setObjectName("app1_1")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.app1_1)
        self.horizontalLayout_13.setContentsMargins(-1, 20, -1, 20)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.appp1_3 = QtWidgets.QFrame(self.app1_1)
        self.appp1_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.appp1_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.appp1_3.setStyleSheet("")
        self.appp1_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.appp1_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.appp1_3.setObjectName("appp1_3")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.appp1_3)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_32 = QtWidgets.QLabel(self.appp1_3)
        self.label_32.setMinimumSize(QtCore.QSize(150, 150))
        self.label_32.setMaximumSize(QtCore.QSize(150, 150))
        self.label_32.setStyleSheet("\n"
"border: 4px;\n"
"border-color:  rgb(102, 255, 139);\n"
"border-radius: 20px;        /* Rounded corners */\n"
"")
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("../SPSCloud_app/img/apps/2.png"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_23.addWidget(self.label_32, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_33 = QtWidgets.QLabel(self.appp1_3)
        self.label_33.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_14.addWidget(self.label_33)
        self.progressBar_3 = QtWidgets.QProgressBar(self.appp1_3)
        self.progressBar_3.setProperty("value", 40)
        self.progressBar_3.setObjectName("progressBar_3")
        self.horizontalLayout_14.addWidget(self.progressBar_3)
        self.verticalLayout_23.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13.addWidget(self.appp1_3)
        self.widget_5 = QtWidgets.QWidget(self.app1_1)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_34 = QtWidgets.QLabel(self.widget_5)
        self.label_34.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_34.setObjectName("label_34")
        self.verticalLayout_24.addWidget(self.label_34)
        self.label_11 = QtWidgets.QLabel(self.widget_5)
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_24.addWidget(self.label_11)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_8.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_8.setMaximumSize(QtCore.QSize(150, 35))
        self.pushButton_8.setStyleSheet("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_24.addWidget(self.pushButton_8)
        self.horizontalLayout_13.addWidget(self.widget_5)
        self.verticalLayout_6.addWidget(self.app1_1)
        self.app1_2 = QtWidgets.QFrame(self.apps_1)
        self.app1_2.setMinimumSize(QtCore.QSize(200, 0))
        self.app1_2.setStyleSheet("#app1_2 {border: 1px solid rgb(158, 159, 159);      /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */}\n"
"\n"
"")
        self.app1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app1_2.setObjectName("app1_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.app1_2)
        self.horizontalLayout_11.setContentsMargins(-1, 20, -1, 20)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.appp1_2 = QtWidgets.QFrame(self.app1_2)
        self.appp1_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.appp1_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.appp1_2.setStyleSheet("")
        self.appp1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.appp1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.appp1_2.setObjectName("appp1_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.appp1_2)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_23 = QtWidgets.QLabel(self.appp1_2)
        self.label_23.setMinimumSize(QtCore.QSize(150, 150))
        self.label_23.setMaximumSize(QtCore.QSize(150, 150))
        self.label_23.setStyleSheet("\n"
"border: 4px;\n"
"border-color:  rgb(102, 255, 139);\n"
"border-radius: 20px;        /* Rounded corners */\n"
"")
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("../SPSCloud_app/img/apps/4.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_21.addWidget(self.label_23, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_31 = QtWidgets.QLabel(self.appp1_2)
        self.label_31.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_12.addWidget(self.label_31)
        self.progressBar_2 = QtWidgets.QProgressBar(self.appp1_2)
        self.progressBar_2.setProperty("value", 67)
        self.progressBar_2.setObjectName("progressBar_2")
        self.horizontalLayout_12.addWidget(self.progressBar_2)
        self.verticalLayout_21.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11.addWidget(self.appp1_2)
        self.widget_4 = QtWidgets.QWidget(self.app1_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_30 = QtWidgets.QLabel(self.widget_4)
        self.label_30.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_30.setObjectName("label_30")
        self.verticalLayout_22.addWidget(self.label_30)
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_22.addWidget(self.label_10)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_7.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_7.setMaximumSize(QtCore.QSize(150, 35))
        self.pushButton_7.setStyleSheet("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_22.addWidget(self.pushButton_7)
        self.horizontalLayout_11.addWidget(self.widget_4)
        self.verticalLayout_6.addWidget(self.app1_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_8.addWidget(self.apps_1)
        self.verticalLayout_11.addWidget(self.frame_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.widget_2 = QtWidgets.QWidget(self.frame_3)
        self.widget_2.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_29 = QtWidgets.QLabel(self.widget_2)
        self.label_29.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_29.setObjectName("label_29")
        self.verticalLayout_3.addWidget(self.label_29, 0, QtCore.Qt.AlignHCenter)
        self.line_4 = QtWidgets.QFrame(self.widget_2)
        self.line_4.setMinimumSize(QtCore.QSize(10, 2))
        self.line_4.setMaximumSize(QtCore.QSize(16777215, 2))
        font = QtGui.QFont()
        font.setBold(True)
        self.line_4.setFont(font)
        self.line_4.setStyleSheet("background-color: rgb(36, 86, 74);\n"
"\n"
" ")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.profile_data_frame = QtWidgets.QFrame(self.widget_2)
        self.profile_data_frame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.profile_data_frame.setStyleSheet("")
        self.profile_data_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profile_data_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profile_data_frame.setObjectName("profile_data_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.profile_data_frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_16 = QtWidgets.QFrame(self.profile_data_frame)
        self.frame_16.setStyleSheet("")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.datos_usuario = QtWidgets.QFrame(self.frame_16)
        self.datos_usuario.setStyleSheet("\n"
"#datos_usuario {\n"
"    /* Your styles here */\n"
"    border: 1px solid rgb(158, 159, 159);     /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.datos_usuario.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.datos_usuario.setFrameShadow(QtWidgets.QFrame.Raised)
        self.datos_usuario.setObjectName("datos_usuario")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.datos_usuario)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_28 = QtWidgets.QLabel(self.datos_usuario)
        self.label_28.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.label_28.setObjectName("label_28")
        self.verticalLayout_17.addWidget(self.label_28)
        self.datos_usuario2 = QtWidgets.QFrame(self.datos_usuario)
        self.datos_usuario2.setStyleSheet("")
        self.datos_usuario2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.datos_usuario2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.datos_usuario2.setObjectName("datos_usuario2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.datos_usuario2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.profile_picture = QtWidgets.QLabel(self.datos_usuario2)
        self.profile_picture.setMinimumSize(QtCore.QSize(150, 150))
        self.profile_picture.setMaximumSize(QtCore.QSize(150, 150))
        self.profile_picture.setSizeIncrement(QtCore.QSize(1, 1))
        self.profile_picture.setBaseSize(QtCore.QSize(0, 0))
        self.profile_picture.setStyleSheet("#profile_picture {\n"
"    border-radius: 5px;\n"
"}")
        self.profile_picture.setLineWidth(1)
        self.profile_picture.setText("")
        self.profile_picture.setPixmap(QtGui.QPixmap("../SPSCloud_app/img/profile/1.png"))
        self.profile_picture.setScaledContents(True)
        self.profile_picture.setObjectName("profile_picture")
        self.horizontalLayout_7.addWidget(self.profile_picture)
        self.frame_5 = QtWidgets.QFrame(self.datos_usuario2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 0px")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 0px")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_19.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 0px")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 0px")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.verticalLayout_19.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../SPSCloud_app/img/recargar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.verticalLayout_19.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7.addWidget(self.frame_5)
        self.verticalLayout_17.addWidget(self.datos_usuario2)
        self.verticalLayout_4.addWidget(self.datos_usuario)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.change_password = QtWidgets.QFrame(self.frame_16)
        self.change_password.setStyleSheet("\n"
"#change_password {\n"
"    /* Your styles here */\n"
"    border: 1px solid rgb(158, 159, 159);     /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.change_password.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.change_password.setFrameShadow(QtWidgets.QFrame.Raised)
        self.change_password.setObjectName("change_password")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.change_password)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_26 = QtWidgets.QLabel(self.change_password)
        self.label_26.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_9.addWidget(self.label_26)
        self.lineEdit_cambiar_contrasena = QtWidgets.QLineEdit(self.change_password)
        self.lineEdit_cambiar_contrasena.setStyleSheet("QLineEdit {\n"
"    background-color: white;        /* White background color */\n"
"    border: 1px solid #d4d4d4;     /* Light gray border */\n"
"    border-radius: 10px;           /* Rounded corners */\n"
"    padding: 5px 10px;             /* Padding around text */\n"
"    font: 14px;                    /* Font size */\n"
"    color: #333333;                /* Text color */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #FF0000;         /* Change border color to red when focused */\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #f3f3f3;     /* Lighter background when disabled */\n"
"    border-color: #e0e0e0;         /* Lighter border when disabled */\n"
"}\n"
"")
        self.lineEdit_cambiar_contrasena.setObjectName("lineEdit_cambiar_contrasena")
        self.verticalLayout_9.addWidget(self.lineEdit_cambiar_contrasena)
        self.label_cambiar_contrasena_warning = QtWidgets.QLabel(self.change_password)
        self.label_cambiar_contrasena_warning.setText("")
        self.label_cambiar_contrasena_warning.setObjectName("label_cambiar_contrasena_warning")
        self.verticalLayout_9.addWidget(self.label_cambiar_contrasena_warning)
        self.pushButton_cambiar_contrasena = QtWidgets.QPushButton(self.change_password)
        self.pushButton_cambiar_contrasena.setObjectName("pushButton_cambiar_contrasena")
        self.verticalLayout_9.addWidget(self.pushButton_cambiar_contrasena)
        self.verticalLayout_4.addWidget(self.change_password)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.change_profile_photo = QtWidgets.QFrame(self.frame_16)
        self.change_profile_photo.setStyleSheet("\n"
"#change_profile_photo {\n"
"    /* Your styles here */\n"
"    border: 1px solid rgb(158, 159, 159);     /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.change_profile_photo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.change_profile_photo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.change_profile_photo.setObjectName("change_profile_photo")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.change_profile_photo)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_27 = QtWidgets.QLabel(self.change_profile_photo)
        self.label_27.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_27.setObjectName("label_27")
        self.verticalLayout_10.addWidget(self.label_27)
        self.frame_7 = QtWidgets.QFrame(self.change_profile_photo)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_cambiar_foto = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_cambiar_foto.setStyleSheet("QLineEdit {\n"
"    background-color: white;        /* White background color */\n"
"    border: 1px solid #d4d4d4;     /* Light gray border */\n"
"    border-radius: 10px;           /* Rounded corners */\n"
"    padding: 5px 10px;             /* Padding around text */\n"
"    font: 14px;                    /* Font size */\n"
"    color: #333333;                /* Text color */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #FF0000;         /* Change border color to red when focused */\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #f3f3f3;     /* Lighter background when disabled */\n"
"    border-color: #e0e0e0;         /* Lighter border when disabled */\n"
"}\n"
"")
        self.lineEdit_cambiar_foto.setObjectName("lineEdit_cambiar_foto")
        self.horizontalLayout_9.addWidget(self.lineEdit_cambiar_foto)
        self.pushButton_select_image = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_select_image.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../SPSCloud_app/img/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_select_image.setIcon(icon1)
        self.pushButton_select_image.setObjectName("pushButton_select_image")
        self.horizontalLayout_9.addWidget(self.pushButton_select_image)
        self.verticalLayout_10.addWidget(self.frame_7)
        self.label_cambiar_foto_warning = QtWidgets.QLabel(self.change_profile_photo)
        self.label_cambiar_foto_warning.setText("")
        self.label_cambiar_foto_warning.setObjectName("label_cambiar_foto_warning")
        self.verticalLayout_10.addWidget(self.label_cambiar_foto_warning)
        self.pushButton_cambiar_foto = QtWidgets.QPushButton(self.change_profile_photo)
        self.pushButton_cambiar_foto.setObjectName("pushButton_cambiar_foto")
        self.verticalLayout_10.addWidget(self.pushButton_cambiar_foto)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem5)
        self.verticalLayout_4.addWidget(self.change_profile_photo)
        self.verticalLayout_7.addWidget(self.frame_16)
        self.verticalLayout_3.addWidget(self.profile_data_frame)
        self.autores_frame = QtWidgets.QFrame(self.widget_2)
        self.autores_frame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.autores_frame.setStyleSheet("\n"
"#autores_frame {\n"
"    /* Your styles here */\n"
"    border: 1px solid rgb(158, 159, 159);     /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.autores_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.autores_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.autores_frame.setObjectName("autores_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.autores_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_22 = QtWidgets.QLabel(self.autores_frame)
        self.label_22.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_5.addWidget(self.label_22)
        self.label_autor1 = QtWidgets.QLabel(self.autores_frame)
        self.label_autor1.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_autor1.setObjectName("label_autor1")
        self.verticalLayout_5.addWidget(self.label_autor1)
        self.label_24 = QtWidgets.QLabel(self.autores_frame)
        self.label_24.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_24.setObjectName("label_24")
        self.verticalLayout_5.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.autores_frame)
        self.label_25.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_5.addWidget(self.label_25)
        self.verticalLayout_3.addWidget(self.autores_frame)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:700; color:#ffffff;\">SPS</span><span style=\" font-size:24pt; color:#ffffff;\">Cloud</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">JUEGOS</span></p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "Dificultad"))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">Birdy Sword</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>Navega a través de obstáculos con un simple toque. ¿Hasta dónde puedes llegar? </p></body></html>"))
        self.pushButton_10.setText(_translate("MainWindow", "Abrir"))
        self.label_42.setText(_translate("MainWindow", "Dificultad"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">SPSClick</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>¿Qué tan rápido puedes clickear? ¡Pon a prueba tu velocidad y reflejos!</p></body></html>"))
        self.pushButton_11.setText(_translate("MainWindow", "Abrir"))
        self.label_33.setText(_translate("MainWindow", "Dificultad"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">SPSHoot</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>Enciende tu cerebro y desafía tus conocimientos en este vibrante juego de trivia.</p></body></html>"))
        self.pushButton_8.setText(_translate("MainWindow", "Abrir"))
        self.label_31.setText(_translate("MainWindow", "Dificultad"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">SPSDungeon</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>Explora las profundidades de mazmorras antiguas, descifra enigmas y combate criaturas místicas en este juego de aventura y estrategia.</p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "Abrir"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">PERFIL</span></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700;\">Tus datos</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Nombre:</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Ejemplo"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>Apellidos:</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Ejemplo"))
        self.label_9.setText(_translate("MainWindow", "Puntaje"))
        self.label_3.setText(_translate("MainWindow", "0"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700;\">Cambiar contraseña</span></p></body></html>"))
        self.lineEdit_cambiar_contrasena.setPlaceholderText(_translate("MainWindow", "Introduce nueva contraseña"))
        self.pushButton_cambiar_contrasena.setText(_translate("MainWindow", "Cambiar contraseña"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700;\">Cambiar foto de perfil</span></p></body></html>"))
        self.lineEdit_cambiar_foto.setPlaceholderText(_translate("MainWindow", "Introduce nueva foto"))
        self.pushButton_cambiar_foto.setText(_translate("MainWindow", "Cambiar foto"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700;\">Autores</span></p></body></html>"))
        self.label_autor1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><a href=\"https://linktr.ee/stanislav_gatin\"><span style=\" text-decoration: underline; color:#094fd1;\">Stanislav Gatin</span></a></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Santiago Álvarez Geanta</p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Pau Mateo Lillo</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
