# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setStyleSheet("border-radius: 0px")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(150, 90))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../SPSCloud_app/img/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setMinimumSize(QtCore.QSize(10, 1))
        self.line_2.setBaseSize(QtCore.QSize(0, 0))
        self.line_2.setStyleSheet("Line {\n"
"    background-color: rgb(53, 68, 76);\n"
"}\n"
"")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_nombre = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_nombre.setStyleSheet("QLineEdit {\n"
"    background-color: white;        /* White background color */\n"
"    border: 1px solid #d4d4d4;     /* Light gray border */\n"
"    border-radius: 10px;           /* Rounded corners */\n"
"    padding: 5px 10px;             /* Padding around text */\n"
"    font: 14px;                    /* Font size */\n"
"    color: #333333;                /* Text color */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #FF0000;         /* Change border color to red when focused */\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #f3f3f3;     /* Lighter background when disabled */\n"
"    border-color: #e0e0e0;         /* Lighter border when disabled */\n"
"}\n"
"")
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        self.horizontalLayout_2.addWidget(self.lineEdit_nombre)
        self.lineEdit_apellidos = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_apellidos.setStyleSheet("QLineEdit {\n"
"    background-color: white;        /* White background color */\n"
"    border: 1px solid #d4d4d4;     /* Light gray border */\n"
"    border-radius: 10px;           /* Rounded corners */\n"
"    padding: 5px 10px;             /* Padding around text */\n"
"    font: 14px;                    /* Font size */\n"
"    color: #333333;                /* Text color */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #FF0000;         /* Change border color to red when focused */\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #f3f3f3;     /* Lighter background when disabled */\n"
"    border-color: #e0e0e0;         /* Lighter border when disabled */\n"
"}\n"
"")
        self.lineEdit_apellidos.setObjectName("lineEdit_apellidos")
        self.horizontalLayout_2.addWidget(self.lineEdit_apellidos)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.lineEdit_login = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_login.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_login.setStyleSheet("QLineEdit {\n"
"    background-color: white;        /* White background color */\n"
"    border: 1px solid #d4d4d4;     /* Light gray border */\n"
"    border-radius: 10px;           /* Rounded corners */\n"
"    padding: 5px 10px;             /* Padding around text */\n"
"    font: 14px;                    /* Font size */\n"
"    color: #333333;                /* Text color */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #FF0000;         /* Change border color to red when focused */\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #f3f3f3;     /* Lighter background when disabled */\n"
"    border-color: #e0e0e0;         /* Lighter border when disabled */\n"
"}\n"
"")
        self.lineEdit_login.setText("")
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.verticalLayout_2.addWidget(self.lineEdit_login)
        self.lineEdit_password = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_password.setStyleSheet("QLineEdit {\n"
"    background-color: white;        /* White background color */\n"
"    border: 1px solid #d4d4d4;     /* Light gray border */\n"
"    border-radius: 10px;           /* Rounded corners */\n"
"    padding: 5px 10px;             /* Padding around text */\n"
"    font: 14px;                    /* Font size */\n"
"    color: #333333;                /* Text color */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #FF0000;         /* Change border color to red when focused */\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #f3f3f3;     /* Lighter background when disabled */\n"
"    border-color: #e0e0e0;         /* Lighter border when disabled */\n"
"}\n"
"")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_2.addWidget(self.lineEdit_password)
        self.label_warnings = QtWidgets.QLabel(self.frame_2)
        self.label_warnings.setStyleSheet("font: 14pt \"Arial\";\n"
"color: rgb(255, 12, 0);")
        self.label_warnings.setText("")
        self.label_warnings.setObjectName("label_warnings")
        self.verticalLayout_2.addWidget(self.label_warnings, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_crearCuenta = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_crearCuenta.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_crearCuenta.setStyleSheet("QPushButton {\n"
"    background-color: #FF0000;  /* Main red color */\n"
"    border: none;               /* No border */\n"
"    color: white;               /* White text color */\n"
"    padding: 8px 15px;         /* Padding around text */\n"
"    font: bold 16px;           /* Bold font with size 16 */\n"
"    border-radius: 5px;        /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E60000; /* Slightly darker shade of red when mouse hovers over */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #CC0000; /* Even darker shade of red when button is pressed */\n"
"}\n"
"")
        self.pushButton_crearCuenta.setObjectName("pushButton_crearCuenta")
        self.horizontalLayout.addWidget(self.pushButton_crearCuenta)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pushButton_back_toLogin = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_back_toLogin.setStyleSheet("QPushButton {\n"
"    background-color: #007ACC;    /* Mid-tone blue */\n"
"    color: white;                 /* White text */\n"
"    border: 1px solid #005A94;    /* Slightly darker blue border */\n"
"    font: bold 12px;              /* Bold font with smaller size */\n"
"    border-radius: 5px;           /* Slightly rounded corners */\n"
"    padding: 5px 10px;            /* Minimal padding */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #008BD4;    /* Lighter blue for hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #006AA8;    /* Darker blue for pressed state */\n"
"}\n"
"")
        self.pushButton_back_toLogin.setObjectName("pushButton_back_toLogin")
        self.horizontalLayout_3.addWidget(self.pushButton_back_toLogin)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700; color:#fd333d;\">SPS</span><span style=\" font-size:18pt; font-weight:700; color:#000000;\">Cloud</span></p></body></html>"))
        self.lineEdit_nombre.setPlaceholderText(_translate("MainWindow", "Nombre"))
        self.lineEdit_apellidos.setPlaceholderText(_translate("MainWindow", "Apellidos"))
        self.lineEdit_login.setPlaceholderText(_translate("MainWindow", "Login"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.pushButton_crearCuenta.setText(_translate("MainWindow", "Crear cuenta"))
        self.pushButton_back_toLogin.setText(_translate("MainWindow", "Log in"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
